import { IMember } from 'src/@types/member';

export const _memberList: IMember[] = [
  {
    id: '1',
    firstName: 'Jorge',
    lastName: 'Marchant',
    secondSurname: 'Brahm',
    role: 'president',
  },
  {
    id: '2',
    firstName: 'Harry',
    lastName: 'Meyer',
    secondSurname: 'Guerrero',
    role: 'vice_president',
  },
  {
    id: '3',
    firstName: 'Ignacio',
    lastName: 'Brintrup',
    secondSurname: 'Bonvallet',
    role: 'secretary',
  },
  {
    id: '4',
    firstName: 'Pablo ',
    lastName: 'Brahm',
    secondSurname: 'Rosas',
    role: 'treasurer',
  },
  {
    id: '5',
    firstName: 'Jaime ',
    lastName: 'Marchant',
    secondSurname: 'Brahm',
    role: 'board_member',
  },
  {
    id: '6',
    firstName: 'Alejandro',
    lastName: 'Wahl',
    secondSurname: 'Böhme',
    role: 'board_member',
  },
  {
    id: '7',
    firstName: 'Enrique',
    lastName: 'Oyarzun ',
    secondSurname: 'Scholtbach',
    role: 'board_member',
  },
  {
    id: '8',
    firstName: 'German ',
    lastName: 'Weitzler',
    secondSurname: 'Zarges',
    role: 'honor_advisor',
  },
  {
    id: '9',
    firstName: 'Henry',
    lastName: 'Scholtbach  ',
    secondSurname: 'Zarges',
    role: 'honor_member',
  },
  {
    id: '10',
    firstName: 'Rodolfo ',
    lastName: 'Stange',
    secondSurname: 'Oelckers',
    role: 'honor_member',
  },
  {
    id: '11',
    firstName: 'Martin',
    lastName: 'Ercoreca',
    secondSurname: 'von Bischoffshausen',
    role: 'honor_member',
  },
  {
    id: '12',
    firstName: 'Federico',
    lastName: 'Oelckers',
    secondSurname: 'Sepulveda',
    role: 'honor_member',
  },
  {
    id: '13',
    firstName: 'Ruben ',
    lastName: 'Alvarado',
    secondSurname: 'Figueroa',
    role: 'member',
  },
  {
    id: '14',
    firstName: 'Daniela',
    lastName: 'Alvarado',
    secondSurname: 'Hermosilla',
    role: 'member',
  },
  {
    id: '15',
    firstName: 'Gerardo',
    lastName: 'Bartsch',
    secondSurname: 'Lohrmann',
    role: 'member',
  },
  {
    id: '16',
    firstName: 'Rudy',
    lastName: 'Bartsch',
    secondSurname: 'Lohrmann',
    role: 'member',
  },
  {
    id: '17',
    firstName: 'Katjia',
    lastName: 'Berndt',
    secondSurname: 'Schuhmacher',
    role: 'member',
  },
  {
    id: '18',
    firstName: 'Jose',
    lastName: 'Berndt',
    secondSurname: 'Sole',
    role: 'member',
  },
  {
    id: '19',
    firstName: 'Juan',
    lastName: 'Berndt',
    secondSurname: 'Sole',
    role: 'member',
  },
  {
    id: '20',
    firstName: 'Thomas',
    lastName: 'Berndt',
    secondSurname: 'Sole',
    role: 'member',
  },
  {
    id: '21',
    firstName: 'Jose',
    lastName: 'Brahm',
    secondSurname: 'Navarrete',
    role: 'member',
  },
  {
    id: '22',
    firstName: 'Ignacio',
    lastName: 'Brintrup',
    secondSurname: 'Bonvallet',
    role: 'member',
  },
  {
    id: '23',
    firstName: 'Jaime ',
    lastName: 'Brintrup',
    secondSurname: 'Bonvallet',
    role: 'member',
  },
  {
    id: '24',
    firstName: 'Lilian',
    lastName: 'Cardenas ',
    secondSurname: 'Elgueta',
    role: 'member',
  },
  {
    id: '25',
    firstName: 'Mauricio',
    lastName: 'Cardenas ',
    secondSurname: 'Elgueta',
    role: 'member',
  },
  {
    id: '26',
    firstName: 'Francisca ',
    lastName: 'Cardenas ',
    secondSurname: 'Elgueta',
    role: 'member',
  },
  {
    id: '27',
    firstName: 'Ignacio ',
    lastName: 'Cardenas ',
    secondSurname: 'Elgueta',
    role: 'member',
  },
  {
    id: '28',
    firstName: 'Mauricio',
    lastName: 'Cardenas ',
    secondSurname: 'Garcia',
    role: 'member',
  },
  {
    id: '29',
    firstName: 'Victor',
    lastName: 'Correa',
    secondSurname: 'Bohle',
    role: 'member',
  },
  {
    id: '30',
    firstName: 'Rolando',
    lastName: 'De Solminihac',
    secondSurname: 'Oelckers',
    role: 'member',
  },
  {
    id: '31',
    firstName: 'Jaime',
    lastName: 'Ercoreca',
    secondSurname: 'Negron',
    role: 'member',
  },
  {
    id: '32',
    firstName: 'Hans',
    lastName: 'Fiebig',
    secondSurname: 'Müller',
    role: 'member',
  },
  {
    id: '33',
    firstName: 'Eduardo',
    lastName: 'Frene',
    secondSurname: 'Dietz',
    role: 'member',
  },
  {
    id: '34',
    firstName: 'Gerardo',
    lastName: 'Fuchslocher',
    secondSurname: 'Marquez',
    role: 'member',
  },
  {
    id: '35',
    firstName: 'Rene ',
    lastName: 'Fuchslocher ',
    secondSurname: 'Raddatz',
    role: 'member',
  },
  {
    id: '36',
    firstName: 'Roberto',
    lastName: 'Gallardo',
    secondSurname: 'Weitzler',
    role: 'member',
  },
  {
    id: '37',
    firstName: 'Helga',
    lastName: 'Georg',
    secondSurname: 'Frese',
    role: 'member',
  },
  {
    id: '38',
    firstName: 'Roberto',
    lastName: 'Gordon ',
    secondSurname: 'Agliati',
    role: 'member',
  },
  {
    id: '39',
    firstName: 'Arturo',
    lastName: 'Guijon ',
    secondSurname: 'Errazuriz',
    role: 'member',
  },
  {
    id: '40',
    firstName: 'Sergio',
    lastName: 'Haeger',
    secondSurname: 'Yunge',
    role: 'member',
  },
  {
    id: '41',
    firstName: 'Adrian ',
    lastName: 'Hamman',
    secondSurname: 'Henkes',
    role: 'member',
  },
  {
    id: '42',
    firstName: 'Nikolas ',
    lastName: 'Heinz',
    secondSurname: 'Davila',
    role: 'member',
  },
  {
    id: '43',
    firstName: 'Byron',
    lastName: 'Herz',
    secondSurname: 'Barria',
    role: 'member',
  },
  {
    id: '44',
    firstName: 'Johann',
    lastName: 'Herz',
    secondSurname: 'Barria',
    role: 'member',
  },
  {
    id: '45',
    firstName: 'Thomas',
    lastName: 'Herz',
    secondSurname: 'Klein',
    role: 'member',
  },
  {
    id: '46',
    firstName: 'Ricardo',
    lastName: 'Hölck',
    secondSurname: 'Kusch',
    role: 'member',
  },
  {
    id: '47',
    firstName: 'Agustin',
    lastName: 'Hölck',
    secondSurname: 'Alvarado',
    role: 'member',
  },
  {
    id: '48',
    firstName: 'Erwin',
    lastName: 'Klein',
    secondSurname: 'Neira',
    role: 'member',
  },
  {
    id: '49',
    firstName: 'Juan',
    lastName: 'Klein',
    secondSurname: 'Schmidt',
    role: 'member',
  },
  {
    id: '50',
    firstName: 'Alejandro',
    lastName: 'Krebs',
    secondSurname: 'Schwerter',
    role: 'member',
  },
  {
    id: '51',
    firstName: 'Camila',
    lastName: 'Kusch',
    secondSurname: 'De La Puente',
    role: 'member',
  },
  {
    id: '52',
    firstName: 'Catalina',
    lastName: 'Kusch',
    secondSurname: 'De La Puente',
    role: 'member',
  },
  {
    id: '53',
    firstName: 'Heinz',
    lastName: 'Kusch',
    secondSurname: 'De La Puente',
    role: 'member',
  },
  {
    id: '54',
    firstName: 'Irene',
    lastName: 'Kusch',
    secondSurname: 'Hechenleitner',
    role: 'member',
  },
  {
    id: '55',
    firstName: 'Rolf',
    lastName: 'Kusch',
    secondSurname: 'Rensinghoff',
    role: 'member',
  },
  {
    id: '56',
    firstName: 'Pedro',
    lastName: 'Laporte',
    secondSurname: 'Miguel',
    role: 'member',
  },
  {
    id: '57',
    firstName: 'Norman',
    lastName: 'Lintz',
    secondSurname: 'Stange',
    role: 'member',
  },
  {
    id: '58',
    firstName: 'Christian',
    lastName: 'Loebel',
    secondSurname: 'Arcos',
    role: 'member',
  },
  {
    id: '59',
    firstName: 'Mario',
    lastName: 'Marchant',
    secondSurname: 'Brahm',
    role: 'member',
  },
  {
    id: '60',
    firstName: 'Joaquin',
    lastName: 'Marchant',
    secondSurname: 'Diaz',
    role: 'member',
  },
  {
    id: '61',
    firstName: 'Jorge',
    lastName: 'Marchant',
    secondSurname: 'Diaz',
    role: 'member',
  },
  {
    id: '62',
    firstName: 'Cristian',
    lastName: 'Marchant',
    secondSurname: 'France',
    role: 'member',
  },
  {
    id: '63',
    firstName: 'Alejandro',
    lastName: 'Marchant',
    secondSurname: 'Hardessen',
    role: 'member',
  },
  {
    id: '64',
    firstName: 'Hernan',
    lastName: 'Marchant',
    secondSurname: 'Hardessen',
    role: 'member',
  },
  {
    id: '65',
    firstName: 'Macarena',
    lastName: 'Marchant',
    secondSurname: 'Martinez',
    role: 'member',
  },
  {
    id: '66',
    firstName: 'Mario',
    lastName: 'Marchant',
    secondSurname: 'Martinez',
    role: 'member',
  },
  {
    id: '67',
    firstName: 'Alberto',
    lastName: 'Marchant',
    secondSurname: 'Olbrich',
    role: 'member',
  },
  {
    id: '68',
    firstName: 'Gaston',
    lastName: 'Marchant',
    secondSurname: 'Roa',
    role: 'member',
  },
  {
    id: '69',
    firstName: 'Rudy',
    lastName: 'Meyer',
    secondSurname: 'Rosemberg',
    role: 'member',
  },
  {
    id: '70',
    firstName: 'Rudy ',
    lastName: 'Meyer',
    secondSurname: 'Ruiz',
    role: 'member',
  },
  {
    id: '71',
    firstName: 'Alejandro',
    lastName: 'Meza',
    secondSurname: 'Werner',
    role: 'member',
  },
  {
    id: '72',
    firstName: 'Konrad',
    lastName: 'Möller-Holtkamp',
    secondSurname: 'Kaiser',
    role: 'member',
  },
  {
    id: '73',
    firstName: 'Rolf',
    lastName: 'Möller-Holtkamp',
    secondSurname: 'Jaederlund',
    role: 'member',
  },
  {
    id: '74',
    firstName: 'Sven',
    lastName: 'Möller-Holtkamp',
    secondSurname: 'Jaederlund',
    role: 'member',
  },
  {
    id: '75',
    firstName: 'Pablo',
    lastName: 'Moore',
    secondSurname: 'Ross',
    role: 'member',
  },
  {
    id: '76',
    firstName: 'Luis',
    lastName: 'Navarro',
    secondSurname: 'Gonzalez',
    role: 'member',
  },
  {
    id: '77',
    firstName: 'Juan',
    lastName: 'Navarro',
    secondSurname: 'Gonzalez',
    role: 'member',
  },
  {
    id: '78',
    firstName: 'Joaquin',
    lastName: 'Neumann',
    secondSurname: 'Heisse',
    role: 'member',
  },
  {
    id: '79',
    firstName: 'Guillermo',
    lastName: 'Neumann',
    secondSurname: 'Perez',
    role: 'member',
  },
  {
    id: '80',
    firstName: 'Jaime',
    lastName: 'Oelckers',
    secondSurname: 'Stange',
    role: 'member',
  },
  {
    id: '81',
    firstName: 'Ignacio',
    lastName: 'Oyarzun',
    secondSurname: 'Aguilera',
    role: 'member',
  },
  {
    id: '82',
    firstName: 'Eduardo ',
    lastName: 'Oyarzun',
    secondSurname: 'Cornejo',
    role: 'member',
  },
  {
    id: '83',
    firstName: 'Alberto ',
    lastName: 'Oyarzun',
    secondSurname: 'Scholtbach',
    role: 'member',
  },
  {
    id: '84',
    firstName: 'Eduardo',
    lastName: 'Oyarzun',
    secondSurname: 'Scholtbach',
    role: 'member',
  },
  {
    id: '85',
    firstName: 'Jaime',
    lastName: 'Pavez',
    secondSurname: 'Cieselski',
    role: 'member',
  },
  {
    id: '86',
    firstName: 'Felipe ',
    lastName: 'Pavez',
    secondSurname: 'Von Freeden',
    role: 'member',
  },
  {
    id: '87',
    firstName: 'Alex',
    lastName: 'Reuter',
    secondSurname: 'Brown',
    role: 'member',
  },
  {
    id: '88',
    firstName: 'Willy',
    lastName: 'Reuter',
    secondSurname: 'Mauret',
    role: 'member',
  },
  {
    id: '89',
    firstName: 'Diego ',
    lastName: 'Reuter',
    secondSurname: 'Möenne-Loccoz',
    role: 'member',
  },
  {
    id: '90',
    firstName: 'Nicolas ',
    lastName: 'Reuter',
    secondSurname: 'Möenne-Loccoz',
    role: 'member',
  },
  {
    id: '91',
    firstName: 'Walter',
    lastName: 'Rinsche',
    secondSurname: 'Andreu',
    role: 'member',
  },
  {
    id: '92',
    firstName: 'Helwin',
    lastName: 'Schmidt',
    secondSurname: 'Gebauer',
    role: 'member',
  },
  {
    id: '93',
    firstName: 'Rene',
    lastName: 'Schmidt',
    secondSurname: 'Gebauer',
    role: 'member',
  },
  {
    id: '94',
    firstName: 'Christian',
    lastName: 'Schmidt',
    secondSurname: 'Himpel',
    role: 'member',
  },
  {
    id: '95',
    firstName: 'Henry',
    lastName: 'Scholtbach',
    secondSurname: 'Schuhmacher',
    role: 'member',
  },
  {
    id: '96',
    firstName: 'Nelson',
    lastName: 'Schwerter',
    secondSurname: 'Siebald',
    role: 'member',
  },
  {
    id: '97',
    firstName: 'Doris',
    lastName: 'Stange',
    secondSurname: 'Münzenmayer',
    role: 'member',
  },
  {
    id: '98',
    firstName: 'Alexa',
    lastName: 'Stange',
    secondSurname: 'Paris',
    role: 'member',
  },
  {
    id: '99',
    firstName: 'Matias',
    lastName: 'Stange',
    secondSurname: 'Paris',
    role: 'member',
  },
  {
    id: '100',
    firstName: 'Claudio ',
    lastName: 'Stange',
    secondSurname: 'Teske',
    role: 'member',
  },
  {
    id: '101',
    firstName: 'Ruby',
    lastName: 'Stange',
    secondSurname: 'Wahl',
    role: 'member',
  },
  {
    id: '102',
    firstName: 'Yola',
    lastName: 'Stange',
    secondSurname: 'Wahl',
    role: 'member',
  },
  {
    id: '103',
    firstName: 'Renato',
    lastName: 'Stolzenbach',
    secondSurname: 'Minte',
    role: 'member',
  },
  {
    id: '104',
    firstName: 'Victor',
    lastName: 'Teuber',
    secondSurname: 'Donoso',
    role: 'member',
  },
  {
    id: '105',
    firstName: 'Rodolfo',
    lastName: 'Wahl',
    secondSurname: 'Böhme',
    role: 'member',
  },
  {
    id: '106',
    firstName: 'Georg',
    lastName: 'Wammes',
    secondSurname: 'Matvienko-Sikar',
    role: 'member',
  },
  {
    id: '107',
    firstName: 'Anton',
    lastName: 'Wammes',
    secondSurname: 'Soto',
    role: 'member',
  },
  {
    id: '108',
    firstName: 'Gabrielle',
    lastName: 'Wammes',
    secondSurname: 'Soto',
    role: 'member',
  },
  {
    id: '109',
    firstName: 'Karl',
    lastName: 'Wammes',
    secondSurname: 'Soto',
    role: 'member',
  },
  {
    id: '110',
    firstName: 'Victor',
    lastName: 'Weitzler',
    secondSurname: 'Stange',
    role: 'member',
  },
  {
    id: '111',
    firstName: 'Alberto',
    lastName: 'Weitzler',
    secondSurname: 'Zarges',
    role: 'member',
  },
  {
    id: '112',
    firstName: 'Helmuth',
    lastName: 'Werner',
    secondSurname: 'Schröder',
    role: 'member',
  },
  {
    id: '113',
    firstName: 'Ruben ',
    lastName: 'Westermaier',
    secondSurname: 'Flores',
    role: 'member',
  },
  {
    id: '114',
    firstName: 'Pilar',
    lastName: 'Winkler',
    secondSurname: 'Ghio',
    role: 'member',
  },
  {
    id: '115',
    firstName: 'Walter',
    lastName: 'Winkler',
    secondSurname: 'Thomas',
    role: 'member',
  },
  {
    id: '116',
    firstName: 'Guillermo',
    lastName: 'Winkler',
    secondSurname: 'Werner',
    role: 'member',
  },
];
